[bindings.swift]
module_name = "KeychatFFI"
ffi_module_name = "keychat_uniffiFFI"
generate_immutable_records = true

[bindings.kotlin]
package_name = "io.keyme.keychat.ffi.uniffi"
generate_immutable_records = true
