/* libkeychat C FFI - Auto-generated by cbindgen. Do not edit. */

#ifndef LIBKEYCHAT_H
#define LIBKEYCHAT_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * Default sliding window size for receiving addresses per peer.
 */
#define DEFAULT_WINDOW_SIZE 3

/**
 * MLS KeyPackage Nostr event kind.
 */
#define KIND_MLS_KEY_PACKAGE 10443

/**
 * Opaque handle holding all keychat state.
 */
typedef struct KeychatContext KeychatContext;

/**
 * Result from sending a friend request.
 */
typedef struct KeychatFriendRequestResult {
  /**
   * Serialized Nostr event JSON (must free with keychat_free_string).
   */
  char *event_json;
  /**
   * The firstInbox address to subscribe to (must free with keychat_free_string).
   */
  char *first_inbox;
  /**
   * 0 on success, non-zero on error.
   */
  int32_t error;
} KeychatFriendRequestResult;

/**
 * Result from receiving a friend request.
 */
typedef struct KeychatFriendReceived {
  char *sender_npub;
  char *sender_name;
  char *sender_signal_id;
  int32_t error;
} KeychatFriendReceived;

/**
 * Send result.
 */
typedef struct KeychatSendResult {
  char *event_json;
  /**
   * New addresses to subscribe to (JSON array string). May be null.
   */
  char *new_addresses_json;
  int32_t error;
} KeychatSendResult;

/**
 * Incoming decrypted message.
 */
typedef struct KeychatMessage {
  char *sender_npub;
  char *content;
  char *kind;
  /**
   * New addresses to subscribe to (JSON array string). May be null.
   */
  char *new_addresses_json;
  int32_t error;
} KeychatMessage;

/**
 * Byte buffer returned from FFI. Caller must free with `keychat_free_buffer()`.
 */
typedef struct KeychatBuffer {
  uint8_t *data;
  uintptr_t len;
} KeychatBuffer;



/**
 * Create a new keychat context from a BIP-39 mnemonic.
 * Returns null on error. The returned pointer must be freed with `keychat_destroy()`.
 */
struct KeychatContext *keychat_init(const char *mnemonic);

/**
 * Create a new keychat context with a freshly generated identity.
 * The mnemonic can be retrieved with `keychat_get_mnemonic()`.
 */
struct KeychatContext *keychat_init_generate(void);

/**
 * Destroy a keychat context and free all associated memory.
 */
void keychat_destroy(struct KeychatContext *ctx);

/**
 * Get the nostr public key (hex). Caller must free with `keychat_free_string()`.
 */
char *keychat_get_npub(const struct KeychatContext *ctx);

/**
 * Get the BIP-39 mnemonic. Caller must free with `keychat_free_string()`.
 */
char *keychat_get_mnemonic(const struct KeychatContext *ctx);

/**
 * Send a friend request to a peer.
 * `peer_npub`: hex nostr pubkey of the peer.
 * `display_name`: your display name.
 *
 * Returns event JSON to publish to relay + firstInbox address to subscribe to.
 */
struct KeychatFriendRequestResult keychat_send_friend_request(struct KeychatContext *ctx,
                                                              const char *peer_npub,
                                                              const char *display_name);

/**
 * Try to parse an incoming event as a friend request. Auto-accepts if it is one.
 * `event_json`: the kind:1059 Nostr event as JSON.
 *
 * Returns sender info on success, error != 0 if not a friend request.
 */
struct KeychatFriendReceived keychat_receive_friend_request(struct KeychatContext *ctx,
                                                            const char *event_json);

/**
 * Encrypt and build a send event for a text message.
 * `peer_npub`: hex nostr pubkey of the recipient (must be an established peer).
 * `text`: message content.
 *
 * Returns the event JSON to publish + any new addresses to subscribe to.
 */
struct KeychatSendResult keychat_send_text(struct KeychatContext *ctx,
                                           const char *peer_npub,
                                           const char *text);

/**
 * Try to decrypt an incoming event from any known peer.
 * `event_json`: the kind:1059 Nostr event as JSON.
 *
 * Returns the decrypted message content + sender + any new addresses.
 */
struct KeychatMessage keychat_receive_event(struct KeychatContext *ctx, const char *event_json);

/**
 * Get the list of peer nostr pubkeys as a JSON array string.
 * Caller must free with `keychat_free_string()`.
 */
char *keychat_list_peers(const struct KeychatContext *ctx);

/**
 * Resolve the correct sending address for a peer.
 * Returns the address string. Caller must free with `keychat_free_string()`.
 */
char *keychat_resolve_send_address(struct KeychatContext *ctx, const char *peer_npub);

/**
 * Free a string returned by any keychat_* function.
 */
void keychat_free_string(char *s);

/**
 * Free a buffer returned by any keychat_* function.
 */
void keychat_free_buffer(struct KeychatBuffer buf);

#endif  /* LIBKEYCHAT_H */
